#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/vendor/autoload.php')) {
	require __DIR__.'/vendor/autoload.php';
} else {
	require __DIR__.'/../../autoload.php';
}

define('WEBDEV_VERSION', '0.4.1');
define('WEBDEV_CONFIG_FILE', __DIR__ .'/config.php');
define('WEBDEV_CONFIGURED', file_exists(WEBDEV_CONFIG_FILE));

\Arakash\Webdev\Webdev::getInstance()->run();