#!/usr/bin/env php
<?php

echo 'the current directory is ' __DIR__ ."\n";
die;
touch(__DIR__ .'/config.php');

if (file_exists(__DIR__.'/vendor/autoload.php')) {
	require __DIR__.'/vendor/autoload.php';
} else {
	require __DIR__.'/../../autoload.php';
}
$app = new Symfony\Component\Console\Application('Webdev', '0.1.0');
$app->add(new Afflicto\Webdev\Console\ConfigCommand);
$app->run();